### ISSUE TITLE
Upgrade to QGIS 3?

### ISSUE THREAD

**Issue by sfkeller** [nextgis/qgis_clickfu#7]
Any plans to upgrade this plugin to QGIS 3?

**Comment by lufticus** [comment]
I'd like to know that too. Or is there an alternative plugin?

Я тоже хотел бы это знать. Или есть альтернативный плагин?

**Comment by sfkeller** [comment]
I've switched to this https://plugins.qgis.org/plugins/latlontools/ => See point 5).

**Comment by lufticus** [comment]
Thank's! It works :)

**Comment by simgislab** [comment]
qgis3 support implemented
